from django.contrib import admin
import xadmin
from .models import *

# Register your models here.

xadmin.site.register(GoodsCategory)
xadmin.site.register(GoodsStyle)
xadmin.site.register(Goods)
xadmin.site.register(Goods_subdivide)
xadmin.site.register(Goods_category)
xadmin.site.register(GoodsImages)
xadmin.site.register(Special)
xadmin.site.register(SpecialGoods)
xadmin.site.register(Idenx_shuixin_Large)
xadmin.site.register(Spec_param)
xadmin.site.register(Spec_param_value)
xadmin.site.register( Spec_param_value_To_Goods_category)
xadmin.site.register(IndexImg)
xadmin.site.register(Idenx_baijiahuayi_little)
xadmin.site.register(Idenx_bihuabeio_little)
xadmin.site.register(Two_zhuanshibianjian_Large)
xadmin.site.register(Two_zhuanshibianjian_little)
xadmin.site.register(Two_bupiruanshi_Large)
xadmin.site.register(Two_bupiruanshi_little)
xadmin.site.register(Two_qiangshibigua_Large)
xadmin.site.register(Two_qiangshibigua_xiandai_Large)
xadmin.site.register(Two_qiangshibigua_xiandai_little)
xadmin.site.register(Two_qiangshibigua_noqiangashi_Large)
xadmin.site.register(Two_qiangshibigua_noqiangashi_little)
xadmin.site.register(Two_qiangshibigua_zhiyazhongshi_Large)
xadmin.site.register(Two_qiangshibigua_zhiyazhongshi_little)
xadmin.site.register(Two_qiangshibigua_langmanmeishi_Large)
xadmin.site.register(Two_qiangshibigua_langmanmeishi_little)
xadmin.site.register(Two_nayixiangxun_Large)
xadmin.site.register(Two_qiangshibigua_xiangxunjingyou_Large)
xadmin.site.register(Two_qiangshibigua_xiangxunjingyou_little)
xadmin.site.register(Two_qiangshibigua_xiangxunlu_Large)
xadmin.site.register(Two_qiangshibigua_xiangxunlu_little)
xadmin.site.register(Two_chuangyijiaju_Large)
xadmin.site.register(Two_chuangyijiaju_chuangyijiaju_little)
xadmin.site.register(Two_chuangyijiaju_shisahngxinying_Large)
xadmin.site.register(Two_chuangyijiaju_shisahngxinying_little)
xadmin.site.register(Two_chuangyishenghuo_chuangyishenghuo_little)

