# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spec_param_value_to_goods_category',
            options={'verbose_name': '所属装饰风格', 'verbose_name_plural': '所属装饰风格'},
        ),
    ]
