# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20190324_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec_param_value',
            name='subdivide',
        ),
    ]
