# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_remove_spec_param_value_subdivide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec_param_value_to_goods_category',
            name='goods_category',
        ),
        migrations.RemoveField(
            model_name='spec_param_value_to_goods_category',
            name='spec_param_value_id',
        ),
        migrations.AlterModelOptions(
            name='spec_param',
            options={'verbose_name': '商品规格key表', 'verbose_name_plural': '商品规格key表'},
        ),
        migrations.AlterModelOptions(
            name='spec_param_value',
            options={'verbose_name': '商品规格value表', 'verbose_name_plural': '商品规格value表'},
        ),
        migrations.AddField(
            model_name='goods_category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Goods.Spec_param_value', verbose_name='商品规格'),
        ),
        migrations.DeleteModel(
            name='Spec_param_value_To_Goods_category',
        ),
    ]
