# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_auto_20190325_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec_param_value_To_Goods_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '商品参数与商品详情关联表',
                'verbose_name_plural': '商品参数与商品详情关联表',
            },
        ),
        migrations.RemoveField(
            model_name='goods_category',
            name='category',
        ),
        migrations.AddField(
            model_name='spec_param_value_to_goods_category',
            name='goods_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_category', verbose_name='关联的所属商品表'),
        ),
        migrations.AddField(
            model_name='spec_param_value_to_goods_category',
            name='spec_param_value_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Spec_param_value', verbose_name='关联的规格参数表'),
        ),
    ]
