# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0005_auto_20190325_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(blank=True, db_index=True, help_text='不需要填写，由程序自动计算', null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale',
            field=models.IntegerField(db_index=True, default=0, verbose_name='销售额'),
        ),
    ]
